# Generated by Django 5.1.4 on 2024-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('income', 'Income'), ('education', 'Education'), ('rent', 'Rent'), ('food', 'Food'), ('groceries', 'Groceries'), ('health', 'Health'), ('maintainance', 'Maintainance')], max_length=50),
        ),
    ]
